---
- name: Debug home
  become: false
  ansible.builtin.debug:
    msg: Home is {{ ansible_env.HOME }}
    
- name: Setup certs
  include_tasks: generate_certs.yml

- name: Setup nginx
  include_tasks: nginx_template.yml

- name: Setup wordpress
  include_tasks: wordpress_template.yml

- name: Setup docke-compose 
  include_tasks: compose_template.yml

- name: Run Docker Compose
  become: true
  shell: "cd {{ ansible_env.HOME }} && docker-compose up -d"